application:
  name: practice
server:
  address: localhost
  port: 8080
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  sql:
    init:
      mode: always
  lifecycle:
    timeout-per-shutdown-phase: 1m
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'   # H2 DB 연결 주소 (In-Memory Mode)
    #url: 'jdbc:h2:~/test'    # H2 DB 연결 주소 (Embedded Mode)
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
#    defer-datasource-initialization: false
